services:
    doctrine.listener:
        class: DomainBundle\EventListener\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }

#    domain.example:
#        class: DomainBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
