slim:
    !imports:
        - './slim.yml'

app:
    timezone: 'Europe/Minsk'

    debug: true
    sqlLog: true

    salt: '!@#$%^&*()'

    database:
        !imports:
            - './database.yml'
