tableprefix : ''
config:
    driver        : pdo_mysql
    host          : localhost
    user          : pms
    password      : pms
    dbname        : pms
    charset       : utf8
    driverOptions :
        1002 : 'SET NAMES utf8'
