dev-phpinfo:
    active: true
    pattern: "/phpinfo"
    methods:
        - "GET"
    callback: "phpinfo"
dev-input:
    active: true
    pattern: "/input"
    methods:
        - "ANY"
    controller: "Dev"
    action: "input"
dev-env:
    active: false
    pattern: "/env"
    methods:
        - "ANY"
    controller: "Dev"
    action: "env"
